frr version 8.4_git
frr defaults traditional
hostname 8cbe0b4b27d9
domainname localdomain
log syslog informational
no ipv6 forwarding
!
router ospf
 ospf router-id 3.3.3.3
 network 172.19.0.0/16 area 0
 network 172.21.0.0/16 area 0
exit
!
