frr version 8.4_git
frr defaults traditional
hostname bea2e3c1d119
domainname localdomain
log syslog informational
no ipv6 forwarding
!
router bgp 65001
 bgp router-id 2.2.2.2
 neighbor 172.18.0.10 remote-as 65001
 neighbor 172.20.0.40 remote-as 65002
exit
!
router ospf
 ospf router-id 2.2.2.2
 network 172.18.0.0/16 area 0
 network 172.21.0.0/16 area 0
exit
!
