frr version 8.4_git
frr defaults traditional
hostname f7085c2604b1
domainname localdomain
log syslog informational
no ipv6 forwarding
!
router bgp 65002
 bgp router-id 4.4.4.4
 neighbor 172.20.0.20 remote-as 65001
exit
!
