frr version 8.4_git
frr defaults traditional
hostname b7441a7710ad
domainname localdomain
log syslog informational
no ipv6 forwarding
!
router bgp 65001
 bgp router-id 1.1.1.1
 neighbor 172.18.0.20 remote-as 65001
exit
!
router ospf
 ospf router-id 1.1.1.1
 network 172.18.0.0/16 area 0
 network 172.19.0.0/16 area 0
exit
!
